[project]
authors = ["Raouf Hecham"]
entry = "main.sw"
license = "Apache-2.0"
name = "fuelmap-template"

[dependencies]
sway_libs = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.24.0" }
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.6.1" }
ownable_nft = { path = "../ownable-nft" }
galaxy_nft = { path = "../galaxy-nft" }
